# Generated by Django 6.0.3 on 2026-03-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_group_permissions_user_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Group',
            new_name='User_Groups',
        ),
    ]
