# Generated by Django 6.0.3 on 2026-03-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_taskstatus_taks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taks',
            new_name='Task',
        ),
    ]
