# Generated by Django 6.0.3 on 2026-03-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_rename_taks_task'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='taskstatus',
            table='companies_task_status',
        ),
    ]
