# Generated by Django 6.0.3 on 2026-03-10 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_taskstatus_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tutle',
            new_name='tittle',
        ),
    ]
