# Generated by Django 6.0.3 on 2026-03-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_tutle_task_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tittle',
            new_name='title',
        ),
    ]
